"""add connect resume

Revision ID: 8c3f27ee292d
Revises: 2ab2aac6c475
Create Date: 2023-12-14 14:26:22.511979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c3f27ee292d"
down_revision: Union[str, None] = "2ab2aac6c475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume_personal_quality")
    op.drop_table("personal_qualities")
    op.add_column(
        "resumes", sa.Column("personal_qualities", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "personal_qualities")
    op.create_table(
        "personal_qualities",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('personal_qualities_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="personal_qualities_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "resume_personal_quality",
        sa.Column("resume_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "personal_quality_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["personal_quality_id"],
            ["personal_qualities.id"],
            name="resume_personal_quality_personal_quality_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"], ["resumes.id"], name="resume_personal_quality_resume_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "resume_id", "personal_quality_id", name="resume_personal_quality_pkey"
        ),
    )
    # ### end Alembic commands ###
