"""vacancy_responses

Revision ID: 2ec6c74145bb
Revises: debb23da47f5
Create Date: 2023-12-05 16:10:48.019854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.vacancy_responses.models import VacancyResponseStatus


# revision identifiers, used by Alembic.
revision: str = "2ec6c74145bb"
down_revision: Union[str, None] = "debb23da47f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancy_response_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("vacancy_response_statuses_pkey")),
    )
    op.create_table(
        "vacancy_responses",
        sa.Column("resume_id", sa.Integer(), nullable=False),
        sa.Column("vacancy_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"], ["resumes.id"], name=op.f("vacancy_responses_resume_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["vacancy_response_statuses.id"],
            name=op.f("vacancy_responses_status_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("vacancy_responses_vacancy_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "resume_id", "vacancy_id", name=op.f("vacancy_responses_pkey")
        ),
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        VacancyResponseStatus.__table__,
        [
            {"id": 1, "name": "Ожидает рассмотрения"},
            {"id": 2, "name": "Просмотрено"},
            {"id": 3, "name": "Отказано"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancy_responses")
    op.drop_table("vacancy_response_statuses")
    # ### end Alembic commands ###
