"""extended companies

Revision ID: bda7c6d0c703
Revises: debb23da47f5
Create Date: 2023-12-05 23:07:18.521710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bda7c6d0c703"
down_revision: Union[str, None] = "debb23da47f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("population", sa.Integer(), nullable=False))
    op.add_column("companies", sa.Column("address", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("phone", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("email", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("logo_path", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "logo_path")
    op.drop_column("companies", "email")
    op.drop_column("companies", "phone")
    op.drop_column("companies", "address")
    op.drop_column("companies", "population")
    # ### end Alembic commands ###
