"""add seed db

Revision ID: debb23da47f5
Revises: 83bfcf02369a
Create Date: 2023-12-02 18:23:15.365295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.resumes.models import Education, Contact, PersonalQuality, EmploymentRecord

# revision identifiers, used by Alembic.
revision: str = 'debb23da47f5'
down_revision: Union[str, None] = '83bfcf02369a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.bulk_insert(
        Education.__table__,
        [
            {'id': 1, 'type': 'Неполное среднее'},
            {'id': 2, 'type': 'Полное среднее'},
            {'id': 3, 'type': 'Высшее'}
        ]
    )

    op.bulk_insert(
        Contact.__table__,
        [
            {'id': 1, 'contact': 'telegram'},
            {'id': 2, 'contact': 'WhatsApp'},
            {'id': 3, 'contact': 'Email'},
            {'id': 4, 'contact': 'Phone'}
        ]
    )

    op.bulk_insert(
        PersonalQuality.__table__,
        [
            {'id': 1, 'description': 'Надежность'},
            {'id': 2, 'description': 'Честность'},
            {'id': 3, 'description': 'Fast API'},
            {'id': 4, 'description': '1С'},

        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
