"""roman mihaylovskih pomidor

Revision ID: 2ab2aac6c475
Revises: f1b2905b82c1
Create Date: 2023-12-11 17:29:54.611855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ab2aac6c475"
down_revision: Union[str, None] = "f1b2905b82c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("population", sa.Integer(), nullable=False))
    op.add_column("companies", sa.Column("address", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("phone", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("email", sa.String(), nullable=False))
    op.add_column("companies", sa.Column("logo_path", sa.String(), nullable=False))
    op.add_column(
        "vacancies", sa.Column("personal_qualities", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "personal_qualities")
    op.drop_column("companies", "logo_path")
    op.drop_column("companies", "email")
    op.drop_column("companies", "phone")
    op.drop_column("companies", "address")
    op.drop_column("companies", "population")
    # ### end Alembic commands ###
