"""add_connect_resume

Revision ID: d2cc9d10f1e0
Revises: 4ca4b45931be
Create Date: 2023-11-28 16:02:17.494417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cc9d10f1e0'
down_revision: Union[str, None] = '4ca4b45931be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
